### ISSUE TITLE
ValidationError: Invalid manifest

### ISSUE THREAD

**Issue by ghost** [hydrotik/node-hapi-react-redux-sass-typescript-mongo-webpack-hmr-gulp#109]
Perhaps the new glue 3.2.0 expects the manifest.js file to be formatted differently?

[dump.txt](https://github.com/hydrotik/node-hapi-react-redux-sass-typescript-mongo-webpack-hmr-gulp/files/183077/dump.txt)

**Comment by hydrotik** [comment]
see 0ebb673..75918e9  upgrade_hapi_glue_3.2.0 -> upgrade_hapi_glue_3.2.0

**Comment by hydrotik** [comment]
60888ecc1275b8feb0978dd64be15c2bd6ff43ae
