### ISSUE TITLE
Create New Account Form

### ISSUE THREAD

**Issue by ghost** [hydrotik/node-hapi-react-redux-sass-typescript-mongo-webpack-hmr-gulp#132]
- Use redux-form for validation
- Update jsonFetch to return Promise, and so taking advantage of redux-form enhancements with Promises
- Enhance server api endpoint for accounts to accept object

**Comment by dhsaks** [comment]
- Use redux-form for validation
- Update jsonFetch to return Promise, and so taking advantage of redux-form enhancements with Promises
- Enhance server api endpoint for accounts to accept object

**Comment by ghost** [comment]
Fixed by #176
