### ISSUE TITLE
node-canvas, pkg-config, and cairo

### ISSUE THREAD

**Issue by ghost** [hydrotik/node-hapi-react-redux-sass-typescript-mongo-webpack-hmr-gulp#170]
pkg-config, cairo and pixman aren't installed by default on OSX and have to be installed manually, it appears.

issue was introduced with pull-request #169. Commit 6421f112b76433b7bf31eb4248d1cc6707671a00 in master

**Comment by ghost** [comment]
Reverted master to before pull-request #169 was merged.

**Comment by hydrotik** [comment]
Should be fixed with last feature/drawing_tool pr
